# Generated by Django 2.2.1 on 2019-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=256, unique=True)),
                ('rounds', models.IntegerField()),
                ('current_round', models.IntegerField()),
            ],
        ),
    ]
