# Generated by Django 2.2.1 on 2019-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('image_url', models.URLField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(default='waitingForPlayers', max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='rounds',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
