# Generated by Django 2.2.1 on 2019-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190520_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Gray')], max_length=256),
        ),
    ]
