# Generated by Django 2.2.1 on 2019-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190520_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Gray'), ('PR', 'Purple'), ('PK', 'Pink'), ('GN', 'Green'), ('YL', 'Yellow')], max_length=2),
        ),
    ]
