# Generated by Django 2.2.1 on 2019-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190520_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_url',
        ),
        migrations.AddField(
            model_name='card',
            name='full_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tagline',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Playset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cards', models.ManyToManyField(to='game.Card')),
            ],
        ),
    ]
