# Generated by Django 2.2.1 on 2019-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190520_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Gray'), ('PR', 'Purple'), ('PK', 'Pink'), ('GN', 'Green'), ('YL', 'Yellow')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
