# Generated by Django 2.2.1 on 2019-05-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190520_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Playset'),
        ),
    ]
