# Generated by Django 2.2.1 on 2019-07-23 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20190608_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Card'),
        ),
    ]
